[package]
name = "scylla-dynamodb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = "0.54.1"
aws-credential-types = "0.54.1"
aws-sdk-dynamodb = "0.24.0"
