[package]
name = "lockpad-derive"
version = { workspace = true }
edition = { workspace = true }

[lib]
proc-macro = true

[dependencies]
aws-sdk-dynamodb.workspace = true
serde_dynamo.workspace = true
syn = "1.0"
scylla-dynamodb = { path = "../scylla-dynamodb" }
quote = "1.0"
