[package]
name = "lockpad-http"
version = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
axum = "0.6.4"
hyper = "0.14.24"
serde = { workspace = true }
thiserror = { workspace = true }
# serde = { version = "1", features = ["derive"] }
# serde_json = "1.0.87"
tokio = { workspace = true }
tower = { version = "0.4", features = ["util"] }
tower-http = { version = "0.3.0", features = ["fs", "cors"] }
tracing = { workspace = true }
