name: tag
on:
  push:
    tags:
      - "*"
jobs:
  publish-crate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v1

      - name: Publish to cargo
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        run: nix develop -c cargo publish -p lockpad-auth

  publish-github:
    name: publish to github releases
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install nix
        uses: cachix/install-nix-action@v15
        with:
          extra_nix_config: |
            access-tokens = github=${{ secrets.GITHUB_TOKEN }}
            extra-substituers = https://cache.garnix.io
            extra-trusted-public-keys = cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g=

      - name: get version
        id: get-version
        run: |
          VERSION=`git describe --tags $(git rev-list --tags --max-count=1)`
          echo ::set-output name=version::"$VERSION"

      - name: generate changelog
        env:
          VERSION: ${{ steps.get-version.outputs.version }}
        run: |
          nix develop .#ci -c cog changelog --at $VERSION -t full_hash > GITHUB_CHANGELOG.md

      - name: generate release
        uses: softprops/action-gh-release@v1
        with:
          body_path: GITHUB_CHANGELOG.md
          tag_name: ${{ steps.get-version.outputs.version }}
  publish-container:
    needs: [publish-github]
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/containers.yaml
    with:
      image_name: lockpad/docker
      repository_name: lockpad
    secrets: inherit
