name: tag
on:
  push:
    tags:
      - "*"
jobs:
  publish-crate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v1

      - name: Publish to cargo
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        run: nix develop -c cargo publish -p lockpad-auth
